/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    FreeRc20: {
      address: "0xd49880bddfac4fd20d3b6bee01c71231c0c63789",
      abi: [
        {
          type: "constructor",
          inputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "DOMAIN_SEPARATOR",
          inputs: [],
          outputs: [
            {
              name: "result",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "allowance",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "result",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "approve",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "result",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "burn",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "decimals",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "mint",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "name",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "nonces",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "result",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "permit",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "deadline",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "v",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "r",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "s",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "symbol",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "totalSupply",
          inputs: [],
          outputs: [
            {
              name: "result",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transfer",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Approval",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Transfer",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AllowanceOverflow",
          inputs: [],
        },
        {
          type: "error",
          name: "AllowanceUnderflow",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientAllowance",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientBalance",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidPermit",
          inputs: [],
        },
        {
          type: "error",
          name: "Permit2AllowanceIsFixedAtInfinity",
          inputs: [],
        },
        {
          type: "error",
          name: "PermitExpired",
          inputs: [],
        },
        {
          type: "error",
          name: "TotalSupplyOverflow",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deploymentFile: "run-1751034195.json",
      deploymentScript: "Deploy.s.sol",
    },
    Metadata: {
      address: "0x45b0bbaceedcfbae96aec2d2ffef70777b0b3ae3",
      abi: [
        {
          type: "constructor",
          inputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "COLORS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "baseSock",
          inputs: [
            {
              name: "baseColorClass",
              type: "string",
              internalType: "string",
            },
            {
              name: "outlineColorClass",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "checkSock",
          inputs: [
            {
              name: "sock",
              type: "tuple",
              internalType: "struct Renderer.Sock",
              components: [
                {
                  name: "baseColorIndex",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "outlineColorIndex",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "top",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "heel",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "toe",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "design",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
              ],
            },
          ],
          outputs: [
            {
              name: "isValid",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "errors",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "decodeSock",
          inputs: [
            {
              name: "encoded",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "sock",
              type: "tuple",
              internalType: "struct Renderer.Sock",
              components: [
                {
                  name: "baseColorIndex",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "outlineColorIndex",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "top",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "heel",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "toe",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "design",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "drawSock",
          inputs: [
            {
              name: "sock",
              type: "tuple",
              internalType: "struct Renderer.Sock",
              components: [
                {
                  name: "baseColorIndex",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "outlineColorIndex",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "top",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "heel",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "toe",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "design",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
              ],
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "encodeSock",
          inputs: [
            {
              name: "sock",
              type: "tuple",
              internalType: "struct Renderer.Sock",
              components: [
                {
                  name: "baseColorIndex",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "outlineColorIndex",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "top",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "heel",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "toe",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "design",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
              ],
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "generateFillStyle",
          inputs: [
            {
              name: "component",
              type: "string",
              internalType: "string",
            },
            {
              name: "sockId",
              type: "string",
              internalType: "string",
            },
            {
              name: "color",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "generateStrokeStyle",
          inputs: [
            {
              name: "component",
              type: "string",
              internalType: "string",
            },
            {
              name: "sockId",
              type: "string",
              internalType: "string",
            },
            {
              name: "color",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "generateStyles",
          inputs: [
            {
              name: "sock",
              type: "tuple",
              internalType: "struct Renderer.Sock",
              components: [
                {
                  name: "baseColorIndex",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "outlineColorIndex",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "top",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "heel",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "toe",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "design",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
              ],
            },
            {
              name: "sockId",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getColor",
          inputs: [
            {
              name: "spot",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "getColorCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "getStyle",
          inputs: [
            {
              name: "index",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "styleIndex",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getTraits",
          inputs: [
            {
              name: "encodedSockId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "attributes",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "render",
          inputs: [
            {
              name: "encodedSockId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "renderSock",
          inputs: [
            {
              name: "sock",
              type: "tuple",
              internalType: "struct Renderer.Sock",
              components: [
                {
                  name: "baseColorIndex",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "outlineColorIndex",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "top",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "heel",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "toe",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "design",
                  type: "tuple",
                  internalType: "struct Renderer.Style",
                  components: [
                    {
                      name: "colorIndex",
                      type: "uint8",
                      internalType: "uint8",
                    },
                    {
                      name: "index",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
              ],
            },
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "styleLookup",
          inputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "styleNames",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "tokenURI",
          inputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "updateStyle",
          inputs: [
            {
              name: "index",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "styleIndex",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "_style",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "validateTokenId",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
      ],
      inheritedFunctions: {},
      deploymentFile: "run-1751034195.json",
      deploymentScript: "Deploy.s.sol",
    },
    SuperSocks: {
      address: "0x8f3024d12c3d702930f2ff98aa8e2261f0be490a",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_metadata",
              type: "address",
              internalType: "address",
            },
            {
              name: "_usdc",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "result",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "balanceOfBatch",
          inputs: [
            {
              name: "owners",
              type: "address[]",
              internalType: "address[]",
            },
            {
              name: "ids",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          outputs: [
            {
              name: "balances",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "cancelOwnershipHandover",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "completeOwnershipHandover",
          inputs: [
            {
              name: "pendingOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "creator",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "creatorBalance",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "creatorFee",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isApprovedForAll",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "result",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "metadata",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract Metadata",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "mint",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "sockIds",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "amounts",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "usdcAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "name",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "result",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "ownershipHandoverExpiresAt",
          inputs: [
            {
              name: "pendingOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "result",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "requestOwnershipHandover",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "safeBatchTransferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "ids",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "amounts",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "data",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "safeTransferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "data",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setApprovalForAll",
          inputs: [
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
            {
              name: "isApproved",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setMetadata",
          inputs: [
            {
              name: "_metadata",
              type: "address",
              internalType: "contract Metadata",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setUsdcPrice",
          inputs: [
            {
              name: "_price",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "slippage",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "supportsInterface",
          inputs: [
            {
              name: "interfaceId",
              type: "bytes4",
              internalType: "bytes4",
            },
          ],
          outputs: [
            {
              name: "result",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "symbol",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "totalCreatorBalance",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "uri",
          inputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "usdc",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "usdcPrice",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawCreatorBalance",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "ApprovalForAll",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "operator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "isApproved",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "CreatorBalanceWithdrawn",
          inputs: [
            {
              name: "creator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "CreatorPaid",
          inputs: [
            {
              name: "sockId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "creator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipHandoverCanceled",
          inputs: [
            {
              name: "pendingOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipHandoverRequested",
          inputs: [
            {
              name: "pendingOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "oldOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SockCreated",
          inputs: [
            {
              name: "sockId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "creator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SocksPaid",
          inputs: [
            {
              name: "total",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "creatorFee",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TransferBatch",
          inputs: [
            {
              name: "operator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "ids",
              type: "uint256[]",
              indexed: false,
              internalType: "uint256[]",
            },
            {
              name: "amounts",
              type: "uint256[]",
              indexed: false,
              internalType: "uint256[]",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TransferSingle",
          inputs: [
            {
              name: "operator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "id",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "URI",
          inputs: [
            {
              name: "value",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "id",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AccountBalanceOverflow",
          inputs: [],
        },
        {
          type: "error",
          name: "AlreadyInitialized",
          inputs: [],
        },
        {
          type: "error",
          name: "ArrayLengthsMismatch",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientBalance",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientUSDC",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidTokenId",
          inputs: [],
        },
        {
          type: "error",
          name: "NewOwnerIsZeroAddress",
          inputs: [],
        },
        {
          type: "error",
          name: "NoHandoverRequest",
          inputs: [],
        },
        {
          type: "error",
          name: "NoUSDCToWithdraw",
          inputs: [],
        },
        {
          type: "error",
          name: "NotOwnerNorApproved",
          inputs: [],
        },
        {
          type: "error",
          name: "TransferToNonERC1155ReceiverImplementer",
          inputs: [],
        },
        {
          type: "error",
          name: "TransferToZeroAddress",
          inputs: [],
        },
        {
          type: "error",
          name: "Unauthorized",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deploymentFile: "run-1751034195.json",
      deploymentScript: "Deploy.s.sol",
    },
    Swapper: {
      address: "0x67f65b834aaac92c15c2eba9ff7e81f2d33a1cfd",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "currency1",
              type: "address",
              internalType: "address",
            },
            {
              name: "_superSocks",
              type: "address",
              internalType: "address payable",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "mintSocksWithETH",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "sockIds",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "amounts",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "minUsdcAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "refundAddress",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "permit2",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IPermit2",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "poolKey",
          inputs: [],
          outputs: [
            {
              name: "currency0",
              type: "address",
              internalType: "Currency",
            },
            {
              name: "currency1",
              type: "address",
              internalType: "Currency",
            },
            {
              name: "fee",
              type: "uint24",
              internalType: "uint24",
            },
            {
              name: "tickSpacing",
              type: "int24",
              internalType: "int24",
            },
            {
              name: "hooks",
              type: "address",
              internalType: "contract IHooks",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "poolManager",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IPoolManager",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "router",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract UniversalRouter",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "superSocks",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract SuperSocks",
            },
          ],
          stateMutability: "view",
        },
      ],
      inheritedFunctions: {},
      deploymentFile: "run-1751034195.json",
      deploymentScript: "Deploy.s.sol",
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
